# Generated by Django 4.2.2 on 2023-06-20 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_status',
            field=models.CharField(choices=[('Order Requested', 'Order Requested'), ('Packaging', 'Packaging'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Order Requested', max_length=50),
        ),
    ]
