# Generated by Django 4.2.2 on 2023-07-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customerprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
