# Generated by Django 4.2.2 on 2023-07-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='modified_by',
        ),
    ]
