# Generated by Django 4.2.2 on 2023-07-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='is_forgot_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userotp',
            name='is_signup',
            field=models.BooleanField(default=False),
        ),
    ]
